"""initial tables

Revision ID: 045311bf3ca4
Revises:
Create Date: 2026-03-24 17:43:01.828115

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "045311bf3ca4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rulings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ruling_number", sa.String(length=50), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column(
            "case_type",
            sa.Enum(
                "CIVIL",
                "CRIMINAL",
                "LABOR",
                "TAX",
                "INTELLECTUAL_PROPERTY",
                "BANKRUPTCY",
                "ADMINISTRATIVE",
                "FAMILY",
                "JUVENILE",
                "ENVIRONMENTAL",
                "OTHER",
                name="casetype",
            ),
            nullable=True,
        ),
        sa.Column("division", sa.String(length=100), nullable=True),
        sa.Column(
            "result",
            sa.Enum(
                "UPHELD",
                "REVERSED",
                "MODIFIED",
                "DISMISSED",
                "APPEAL_DISMISSED",
                "APPEAL_REVERSED",
                "OTHER",
                name="rulingresult",
            ),
            nullable=True,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("facts", sa.Text(), nullable=True),
        sa.Column("issues", sa.Text(), nullable=True),
        sa.Column("judgment", sa.Text(), nullable=True),
        sa.Column("full_text", sa.Text(), nullable=False),
        sa.Column("keywords", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("referenced_sections", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("pdf_url", sa.String(length=500), nullable=True),
        sa.Column("qdrant_id", sa.String(length=100), nullable=True),
        sa.Column("is_processed", sa.Boolean(), nullable=False),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rulings_case_type"), "rulings", ["case_type"], unique=False
    )
    op.create_index(op.f("ix_rulings_id"), "rulings", ["id"], unique=False)
    op.create_index(
        op.f("ix_rulings_is_processed"), "rulings", ["is_processed"], unique=False
    )
    op.create_index(
        op.f("ix_rulings_qdrant_id"), "rulings", ["qdrant_id"], unique=False
    )
    op.create_index(op.f("ix_rulings_result"), "rulings", ["result"], unique=False)
    op.create_index(
        op.f("ix_rulings_ruling_number"), "rulings", ["ruling_number"], unique=True
    )
    op.create_index(op.f("ix_rulings_year"), "rulings", ["year"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "auth_provider",
            sa.Enum("EMAIL", "GOOGLE", "LINE", name="authprovider"),
            nullable=False,
        ),
        sa.Column(
            "subscription_tier",
            sa.Enum("FREE", "PRO", "ENTERPRISE", name="subscriptiontier"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("daily_search_count", sa.Integer(), nullable=False),
        sa.Column("last_search_date", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "bookmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ruling_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["ruling_id"],
            ["rulings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "ruling_id", name="uq_user_ruling"),
    )
    op.create_index(op.f("ix_bookmarks_id"), "bookmarks", ["id"], unique=False)
    op.create_index(
        op.f("ix_bookmarks_ruling_id"), "bookmarks", ["ruling_id"], unique=False
    )
    op.create_index(
        op.f("ix_bookmarks_user_id"), "bookmarks", ["user_id"], unique=False
    )
    op.create_table(
        "search_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("search_type", sa.String(length=20), nullable=False),
        sa.Column("results_count", sa.Integer(), nullable=False),
        sa.Column("filters_applied", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_search_history_id"), "search_history", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_search_history_user_id"), "search_history", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_search_history_user_id"), table_name="search_history")
    op.drop_index(op.f("ix_search_history_id"), table_name="search_history")
    op.drop_table("search_history")
    op.drop_index(op.f("ix_bookmarks_user_id"), table_name="bookmarks")
    op.drop_index(op.f("ix_bookmarks_ruling_id"), table_name="bookmarks")
    op.drop_index(op.f("ix_bookmarks_id"), table_name="bookmarks")
    op.drop_table("bookmarks")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_rulings_year"), table_name="rulings")
    op.drop_index(op.f("ix_rulings_ruling_number"), table_name="rulings")
    op.drop_index(op.f("ix_rulings_result"), table_name="rulings")
    op.drop_index(op.f("ix_rulings_qdrant_id"), table_name="rulings")
    op.drop_index(op.f("ix_rulings_is_processed"), table_name="rulings")
    op.drop_index(op.f("ix_rulings_id"), table_name="rulings")
    op.drop_index(op.f("ix_rulings_case_type"), table_name="rulings")
    op.drop_table("rulings")
    # Drop PostgreSQL enum types created by the tables
    op.execute("DROP TYPE IF EXISTS casetype")
    op.execute("DROP TYPE IF EXISTS rulingresult")
    op.execute("DROP TYPE IF EXISTS authprovider")
    op.execute("DROP TYPE IF EXISTS subscriptiontier")
    # ### end Alembic commands ###
